# Generated by Django 5.2.3 on 2026-01-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0003_dietplan_dietstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customer')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.dietplan')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDietStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('customer_diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customerdietplan')),
                ('diet_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.dietstep')),
            ],
        ),
    ]
