# Generated by Django 5.2.10 on 2026-01-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0007_customer_is_verified_customer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
