# Generated by Django 5.2.10 on 2026-01-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0008_alter_customer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp',
        ),
    ]
