# Generated by Django 5.2.10 on 2026-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0009_remove_customer_is_verified_remove_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
