# Generated by Django 5.2.10 on 2026-01-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0011_food_dietplanfood_customerfoodlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplanfood',
            name='diet_plan',
        ),
        migrations.RemoveField(
            model_name='dietplanfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='food',
            name='dietician',
        ),
        migrations.DeleteModel(
            name='CustomerFoodLog',
        ),
        migrations.DeleteModel(
            name='DietPlanFood',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
