# Generated by Django 5.2.10 on 2026-01-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0016_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
