# Generated by Django 5.2.10 on 2026-01-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0020_remove_workoutstep_workout_plan_delete_workoutplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='workout_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.dietician')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='workout_steps/')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.workoutplan')),
            ],
        ),
    ]
