# Generated by Django 5.2.10 on 2026-01-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0021_workoutplan_workoutstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutstep',
            name='workout_plan',
        ),
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
        migrations.DeleteModel(
            name='WorkoutStep',
        ),
    ]
