# Generated by Django 5.1.6 on 2026-01-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0023_workoutplan_workoutstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customer')),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.dietician')),
            ],
        ),
    ]
