# Generated by Django 5.1.6 on 2026-01-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0024_dietplanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customer'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
