# Generated by Django 5.1.6 on 2026-01-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0025_dietplan_customer_dietplan_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='is_custom',
        ),
    ]
