# Generated by Django 5.1.6 on 2026-01-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0026_remove_dietplan_customer_remove_dietplan_is_custom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietPlanRequest',
        ),
    ]
