# Generated by Django 5.1.6 on 2026-01-31 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0028_dietcustomizationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customer')),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.dietcustomizationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDietStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_text', models.TextField()),
                ('custom_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='nutri_app.customdietplan')),
            ],
        ),
    ]
