# Generated by Django 5.1.6 on 2026-01-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0029_customdietplan_customdietstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdietstep',
            name='custom_plan',
        ),
        migrations.DeleteModel(
            name='CustomDietPlan',
        ),
        migrations.DeleteModel(
            name='CustomDietStep',
        ),
    ]
