# Generated by Django 5.1.6 on 2026-01-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0031_customdietplan_customdietstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdietstep',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
