# Generated by Django 5.2.10 on 2026-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0032_customdietstep_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='workout_videos/'),
        ),
    ]
