# Generated by Django 5.2.10 on 2026-03-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0033_workoutplan_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietician',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='dietician/license/'),
        ),
    ]
