# Generated by Django 5.2.10 on 2026-03-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0034_dietician_license_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdietplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
