# Generated by Django 5.2.10 on 2026-03-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0035_customerdietplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdietplan',
            name='status',
        ),
    ]
