# Generated by Django 5.2.10 on 2026-03-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0036_remove_customerdietplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
