# Generated by Django 5.2.10 on 2026-03-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0038_dietfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmr', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customer')),
            ],
        ),
    ]
