# Generated by Django 5.2.10 on 2026-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0039_customerbmr'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
