# Generated by Django 5.2.10 on 2026-03-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0040_workoutplan_is_free_workoutplan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.workoutplan')),
            ],
            options={
                'unique_together': {('customer', 'plan')},
            },
        ),
    ]
