# Generated by Django 5.2.10 on 2026-03-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0041_workoutpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.workoutplan')),
            ],
        ),
    ]
